### ISSUE TITLE
[BUG] Skills aren't all registering properly

### ISSUE THREAD

**Issue by mikejgray** [NeonGeckoCom/NeonCore#424]
### Description

Some skills are not registering properly on the latest pre-release.

### Steps to Reproduce

`pip install neon-homeassistant-skill==0.0.12a1`
Deactivate the home assistant skill
Reactivate the skill

```
 22:12:55.810 - skills - mycroft.skills.skill_manager:deactivate_skill:725 - INFO - Deactivating skill: neon_homeassistant_skill.mikejgray
 22:12:55.818 - skills - mycroft.skills.skill_loader:_execute_instance_shutdown:432 - INFO - Skill neon_homeassistant_skill.mikejgray shut down successfully
 22:12:58.709 - skills - mycroft.skills.skill_manager:activate_skill:754 - ERROR - Couldn't activate skill
Traceback (most recent call last):
  File "/home/neon/venv/lib/python3.7/site-packages/mycroft/skills/skill_manager.py", line 752, in activate_skill
    skill_loader.activate()
  File "/home/neon/venv/lib/python3.7/site-packages/mycroft/skills/skill_loader.py", line 419, in activate
    self.load()
TypeError: load() missing 1 required positional argument: 'skill_class'
 22:14:51.057 - skills - mycroft.skills.skill_manager:deactivate_skill:725 - INFO - Deactivating skill: neon_homeassistant_skill.mikejgray
 22:14:53.357 - skills - mycroft.skills.skill_manager:activate_skill:754 - ERROR - Couldn't activate skill
Traceback (most recent call last):
  File "/home/neon/venv/lib/python3.7/site-packages/mycroft/skills/skill_manager.py", line 752, in activate_skill
    skill_loader.activate()
  File "/home/neon/venv/lib/python3.7/site-packages/mycroft/skills/skill_loader.py", line 419, in activate
    self.load()
TypeError: load() missing 1 required positional argument: 'skill_class'
```

### Relevant Code

I believe it's in ovos-workshop.

### Other Notes

Seems to not be an issue for OVOSSkill-based skills

**Comment by NeonDaniel** [comment]
```
2023-05-17 10:38:20.581 - skills - mycroft.skills.skill_loader:_communicate_load_status:554 - INFO - Skill neon_homeassistant_skill.mikejgray loaded successfully
...
(venv) neon@neon:~$ mana unload-skill neon_homeassistant_skill.mikejgray
Requested unload of: neon_homeassistant_skill.mikejgray
...
2023-05-17 10:39:31.177 - skills - mycroft.skills.skill_manager:deactivate_skill:725 - INFO - Deactivating skill: neon_homeassistant_skill.mikejgray
2023-05-17 10:39:31.226 - skills - mycroft.skills.skill_loader:_execute_instance_shutdown:432 - INFO - Skill neon_homeassistant_skill.mikejgray shut down successfully
...
(venv) neon@neon:~$ mana load-skill neon_homeassistant_skill.mikejgray
Requested load of: neon_homeassistant_skill.mikejgray
...
2023-05-17 10:40:06.046 - skills - mycroft.skills.skill_loader:_communicate_load_status:554 - INFO - Skill neon_homeassistant_skill.mikejgray loaded successfully
2023-05-17 10:40:06.058 - skills - mycroft.skills.intent_services.padatious_service:_register_object:262 - DEBUG - Registering Padatious intent: neon_homeassistant_skill.mikejgray:lights.increase.brightness.intent
2023-05-17 10:40:06.078 - skills - mycroft.skills.intent_services.padatious_service:_register_object:262 - DEBUG - Registering Padatious intent: neon_homeassistant_skill.mikejgray:lights.set.brightness.intent
2023-05-17 10:40:06.207 - neon_homeassistant_skill.mikejgray - INFO - <class 'dict'>
2023-05-17 10:40:06.207 - neon_homeassistant_skill.mikejgray - INFO - <class 'dict'>
2023-05-17 10:40:06.209 - neon_homeassistant_skill.mikejgray - INFO - {}
2023-05-17 10:40:06.209 - neon_homeassistant_skill.mikejgray - INFO - {}
```
