### ISSUE TITLE
[BUG] no fallback error

### ISSUE THREAD

**Issue by denics** [NeonGeckoCom/NeonCore#513]
### Description

If no fallback action is registered and no results is given, neon generates an error:
```
2023-07-30 15:34:35.162 - skills - neon_core.skills.patched_common_query:_query_timeout:228 - INFO - Check responses with 0 replies
2023-07-30 15:34:36.023 - skills - ovos_utils.file_utils:resolve_resource_file:152 - WARNING - Deprecation version=0.1.0. Caller=ovos_utils.sound:94. Expected a dict config and got None.
2023-07-30 15:34:36.078 - skills - mycroft.skills.intent_service:handle_utterance:336 - ERROR - stat: path should be string, bytes, os.PathLike or integer, not NoneType
Traceback (most recent call last):
  File "/home/neon/venv/lib/python3.7/site-packages/mycroft/skills/intent_service.py", line 333, in handle_utterance
    self.send_complete_intent_failure(message)
  File "/home/neon/venv/lib/python3.7/site-packages/mycroft/skills/intent_service.py", line 344, in send_complete_intent_failure
    play_error_sound()
  File "/home/neon/venv/lib/python3.7/site-packages/ovos_utils/sound/__init__.py", line 94, in play_error_sound
    read_mycroft_config().get('sounds', {}).get('error'))
  File "/home/neon/venv/lib/python3.7/site-packages/ovos_utils/file_utils.py", line 161, in resolve_resource_file
    if os.path.isfile(res_name):
  File "/usr/local/lib/python3.7/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
```

### Steps to Reproduce

- remove all skills
- ask something
- you get the error

**Comment by NeonDaniel** [comment]
It looks like I'm missing a default resource for the error sound that plays when no skill (including fallbacks) handles a request. #510 added the config, but not the resource file
